* All-in-one Embedded Tutorial With =Raspberrypi RP2040 MCU=

In this tutorial, we will cover all the pieces of knowledge we need to know for using =C= and =Zig= to do embedded programming.

Although we're targeting the =RP2040 MCU=, in fact, we still need an MCU board that has the =RP2040= to run all demo codes. That's why we pick the =Raspberrypi Pico-W= as our target board to run all the demos.

** The major purposes of this tutorial: 

1. Learn the fundamental concepts and knowledge for embedded programming from scratch, what we've learned is NOT limited to Raspberry Pi RP2040 MCU, actually, it benefits all MCUs as well1.

2. The real-world demo to show how to use =C= and =Zig= in embedded programming.

3. How to mix =Zig= and =C= in low-level hardware development.


**  =RP2040 MCU= and =Raspberry Pi Pico W= board datasheet

All demos in this tutorial use the [[https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html#the-family][Raspberry Pi Pico W]] microcontroller, you can download the related resources from here: 

*** Major datasheets

The following data sheets are the major knowledge sources that we will learn from, as we need to know the fundamental concepts and terms about MCU programming, that's the best resource. 

- [[https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf][RP2040 datasheet]]

- [[https://documentation-service.arm.com/static/620545c494e7af28dd7c9cbc][Arm Cortex-M0+ Processor Datasheet]]


*** Pin and PCB related

- [[https://datasheets.raspberrypi.com/rp2040/hardware-design-with-rp2040.pdf][Hardware design with RP2040]] (Just in case you want to build your own PCB with minimal design to work with =RP2040= MCU)

- [[https://datasheets.raspberrypi.com/picow/PicoW-A4-Pinout.pdf][Pico Pinout Diagram]] 

- [[https://datasheets.raspberrypi.com/picow/pico-w-datasheet.pdf][Pico W datasheet]]


*** Pico/Pico W C/C++ SDK related

In the first demo, we will learn how to use MCU registers to control MCU, as that's fundamental to how the MCU works. But usually, you should choose to use the existing C/C++ SDK (to call APIs) to deal with RP2040 to get a faster development cycle. 

- [[https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf][Pico W C/C++ SDK]]

- [[https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf][Getting started with Pico]] (how to debug pico)

- [[https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf][Pico W WIFI and Bluetooth]]



** Folder structure

#+BEGIN_SRC bash
  .
  ├── c-demos                              # C demos
  │   ├── cmake-build-process.org          # Explain how cmake builds your pico program
  │   ├── blinking-led-register            # Particular demo project
  │   │   ├── build.sh                     # Project scope build script
  │   │   ├── CMakeLists.txt               # Project scope CMake configuration file
  │   │   ├── configure.sh                 # Project scope configure script to init CMake
  │   │   ├── flash_linux.sh               # Project scope script to flash your program to Pico hardware via USB-C
  │   │   ├── pico_sdk_import.cmake        # `pico-sdk CMake` configuration (copied from PICO_SDK)
  │   │   ├── README.md                    # Project scope README
  │   │   └── src                          # source code files inside
  │   └── ...                              # Another C demos projects
  ├── zig-demos                            # Zig demos
  ├── README.org                           # This file
  └── tutorial                             # Tutorials fold
      ├── 1-glossary-of-terms.org          # Tutorail chapter files
      ├── 2-basic-concepts.org             # Tutorail chapter files
      └── ...                              # Tutorail chapter files

#+END_SRC


** Tutorial chapters

[[file:tutorial/1-glossary-of-terms.org][1. Glossary of terms]]

[[file:tutorial/2-basic-concepts.org][2. Basic concepts]]

3. Install tooling

   [[file:tutorial/3-1-a-install-arm-gnu-toolchain.org][3.1. Install ARM GNU Toolchain]]

   [[file:tutorial/3-1-b-setup-pico-sdk.org][3.2. Setup PICO C/C++ SDK]]

   [[file:tutorial/3-1-c-setup-pico-examples.org][3.3. Setup PICO Examples when you needed]]

4. Write your first program and run on =Pico W=

   [[file:tutorial/4-1-a-how-does-your-program-tells-mcu-what-to-do.org][4.1 How does your program tell MCU what to do]]

   [[file:tutorial/4-2-a-bitwise-to-control-mcu-register.org][4.2 Bitwise operations to control =RP2040= register]]

   [[file:tutorial/4-3-a-blinking-led-by-rp2040-register.org][4.3 Blinking led by the RP2040 register]]

5. The important things you need to know about the C/C++ SDK

   5.1 [[file:tutorial/5-1-a-why-sdk-enable-all-peripherals-by-default.org][Why SDK enables all peripherals by default]]

   5.1 How ~printf~ is able to print to USB and UART
