* Print the =SP (Stack Pointer)= and =PC (Program Counter)= pointer address demo

** How to configure

You have a few options to configure depending on different environment variable settings:

| Env var name        | Description                                                            |
|---------------------+------------------------------------------------------------------------|
| =PICO_SDK_PATH=       | Your =pico-sdk= git clone folder.                                        |
|                     |                                                                        |
| =PICO_TOOLCHAIN_PATH= | If ~arm-none-eabi-gcc~ doesn't in your ~$PATH~.                            |
|                     |                                                                        |


For example:

#+BEGIN_SRC bash
  # Option 1
  PICO_SDK_PATH=~/pico/pico-sdk \
  ./configure.sh

  # Option 2
  PICO_SDK_PATH=~/pico/pico-sdk \
  PICO_TOOLCHAIN_PATH=~/Downloads/arm-gnu-toolchain/bin \
  ./configure.sh
#+END_SRC


** How to build and flash pico

Build the entire project:

   #+BEGIN_SRC bash
     ./build.sh
   #+END_SRC


Then run ~./flash_linux.sh~ or ~/.flash_macos.sh~ script, it will print out the usage and example if you don't provide any parameter.

#+BEGIN_SRC bash
  # For linux
  doas ./flash_linux.sh print-pointer-address

  # For macos
  ./flash_macos.sh print-pointer-address
#+END_SRC


** How to view ~printf~ debug output

Run ~./minicom.sh~ script, it will print out the usage and example if you don't provide any parameter.

#+BEGIN_SRC bash
  # Welcome to minicom 2.8

  # OPTIONS:
  # Compiled on Jan  4 2021, 00:04:46.
  # Port /dev/tty.usbmodem14301, 15:16:36

  # Press Meta-Z for help on special keys

  >>> [ Print Pointer Address Demo]
  >>> Program counter pointer address: 0x1000031A
  >>> Stack pointer address: 0x20041FF4
#+END_SRC

BTW, the ~Meta-Z~ doesn't work on =MacOS + Alacritty= at this moment. So, =kill minicom= is my way to exit the =minicom= program.
